### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by pyscripter** [Purik/AIO#1]
Can the library be used in 64bits applications?

I can see that ApiRedirect in MonkeyPatch.pas is 32bits only.

**Comment by PavelMinenkov** [comment]
Yes, I will implement x64 support as soon as possible for MonkeyPatch. 
But it is true only for monkey-patching, all other parts of AIO use Win-Fibers so they are x64 compatible

**Comment by pyscripter** [comment]
It looks like Monkeypatch is necessary for using AIO in GUI (Vcl) applications.  Is this correct?

**Comment by PavelMinenkov** [comment]
It's correct, Monkeypatching free from the necessity to implement yourself message loop

**Comment by pyscripter** [comment]
Maybe the following code from https://stackoverflow.com/questions/8978177/patch-routine-call-in-delphi would do the trick.

```
type
  PAbsoluteIndirectJmp = ^TAbsoluteIndirectJmp;
  TAbsoluteIndirectJmp = packed record
    OpCode: Word;  // $FF25(Jmp, FF /4) 
    Addr: DWORD;  // 32-bit address
                  // in 32-bit mode: it is a direct jmp address to target method
                  // in 64-bit mode: it is a relative pointer to a 64-bit address used to jmp to target method
  end;

  PInstruction = ^TInstruction;
  TInstruction = packed record
    Opcode: Byte;
    Offset: Integer;
  end;


function GetActualAddr(Proc: Pointer): Pointer;
begin
  Result := Proc;
  if Result <> nil then
    if PAbsoluteIndirectJmp(Result)^.OpCode = $25FF then  // we need to understand if it is proc entry or a jmp following an address
{$ifdef CPUX64}
      Result := PPointer( NativeInt(Result) + PAbsoluteIndirectJmp(Result)^.Addr + SizeOf(TAbsoluteIndirectJmp))^;
      // in 64-bit mode target address is a 64-bit address (jmp qword ptr [32-bit relative address] FF 25 XX XX XX XX)
      // The address is in a loaction pointed by ( Addr + Current EIP = XX XX XX XX + EIP)
      // We also need to add (instruction + operand) size (SizeOf(TAbsoluteIndirectJmp)) to calculate relative address
      // XX XX XX XX + Current EIP + SizeOf(TAbsoluteIndirectJmp)
{$else}
      Result := PPointer(PAbsoluteIndirectJmp(Result)^.Addr)^;
      // in 32-bit it is a direct address to method
{$endif}
end;

procedure PatchCode(Address: Pointer; const NewCode; Size: Integer);
var
  OldProtect: DWORD;
begin
  if VirtualProtect(Address, Size, PAGE_EXECUTE_READWRITE, OldProtect) then //FM: remove the write protect on Code Segment
  begin
    Move(NewCode, Address^, Size);
    FlushInstructionCache(GetCurrentProcess, Address, Size);
    VirtualProtect(Address, Size, OldProtect, @OldProtect); // restore write protection
  end;
end;

procedure RedirectProcedure(OldAddress, NewAddress: Pointer);
var
  NewCode: TInstruction;
begin
  OldAddress := GetActualAddr(OldAddress); 

  NewCode.Opcode := $E9;//jump relative
  NewCode.Offset := NativeInt(NewAddress) - NativeInt(OldAddress) - SizeOf(NewCode);

  PatchCode(OldAddress, NewCode, SizeOf(NewCode));
end;
```

**Comment by PavelMinenkov** [comment]
I've done, ENJOY!!!

**Comment by pyscripter** [comment]
Thank you.
I wonder however if 
`
NewCode.Offset := NativeInt(NewAddress) - NativeInt(OldAddress) - SizeOf(NewCode);
`
will fail if the RHS overflows the integer NewCode.Offset in 64bit.

**Comment by PavelMinenkov** [comment]
I intercept OS calls by that lib: https://github.com/MahdiSafsafi/delphi-detours-library

**Comment by pyscripter** [comment]
That should be safe.  Great!

**Comment by PavelMinenkov** [comment]
What project do you develop?

**Comment by pyscripter** [comment]
https://github.com/pyscripter/python4delphi/
https://github.com/pyscripter/pyscripter/

**Comment by PavelMinenkov** [comment]
Do you want sell products?

**Comment by pyscripter** [comment]
What do you mean?

**Comment by PavelMinenkov** [comment]
Do you develop listed above projects as hobby?

**Comment by pyscripter** [comment]
Mainly yes.  I sometimes get sponsorship for certain features and occasionally donations.  How about you?

**Comment by PavelMinenkov** [comment]
Im new in publishing source code. What do you think about commercial part of Aio? Can I get sponsorship? How do you do that?

**Comment by pyscripter** [comment]
Aio looks great, but from my experience it is very difficult to make a living from open source projects.  PyScripter in the last four years has had 700K downloads and millions since it was first introduced.  But very few users donate.  

The alternative would be to do freelance contract work.  If you look at the Delphi newsgroups, you will find quite few opportunities.  In fact, if you do want to do some paid work email me at pyscripter@gmail.com.

**Comment by PavelMinenkov** [comment]
Sent email

**Comment by pyscripter** [comment]
And I replied!

**Comment by PavelMinenkov** [comment]
Received, I will check sources and will give answer as soon as possible
